# Generated by Django 5.1.1 on 2024-10-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
